### ISSUE TITLE
Alembic for HL

### ISSUE THREAD

**Issue by TripleHeadedSheep** [Angry-Pixel/The-Betweenlands#177]
Alembic: Doesnt do anything yet (I know nothing was supposed to happen yet). But the block model also renders incorrect. Transparent parts are solid.

**Comment by MrCompost** [comment]
Hmm... aside from the rendering which was simply changed (I suppose it can be changed back easily enough) the animator works fine to me.
The compost bin just needs a sort of list of items adding, only a line of code or two. Other than that it just needs rendering done.
For the pestle and mortar, what bits do you mean exactly? If its just the pestle, then that's intentional because it renders when its doing its thing.
The Alembic was just added quickly to get it in, its veeeeeery unfinished. The transparency issue can be fixed easily, even I could do that =P

**Comment by TripleHeadedSheep** [comment]
Animator spawns in a life crystal and a stack of sulphur, which gets used up, but nothing happens to the item scroll.

P&M misses some wooden details between the legs and a bush of dried herbs:
![image](https://cloud.githubusercontent.com/assets/5305563/9025772/72170e20-3914-11e5-8c9c-7100b7ccd1f3.png)
![image](https://cloud.githubusercontent.com/assets/5305563/9025777/85a810d8-3914-11e5-9066-0855f6d8828d.png)

**Comment by MrCompost** [comment]
I still can't find anything wrong with the Animator but I see what you mean about the Mortar.

**Comment by vadis365** [comment]
Updated this issue and removed all the crap! (added some more crap) :P

**Comment by MrCompost** [comment]
You sure do...

**Comment by MrCompost** [comment]
Closed until Len gets back.

**Comment by TheCyberBrick** [comment]
I think this is finished

**Comment by MrCompost** [comment]
Hurrah :D
