### ISSUE TITLE
Custom menu

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#230]
Ok, so we need to get this polished up so we can compile the mod and release the new version. 
Here's what we need - 

Defo - 
Custom music (we have 3 tracks)

Possibly - 
Custom button textures
Replace the dirt background in the other menus with something more fitting e.g temple brick
A button to switch back to the vanilla menu
Any other small bits that people think of

Plus I'll tweak the textures here and there.

**Comment by MrCompost** [comment]
Any news on this?

**Comment by SupernovaCo** [comment]
I could maybe make some assets for this... (besides the logo, you already have that)

**Comment by Sevenoon** [comment]
Oops, forgot to show you, I have a WIP title screen, but I kinda made it to show you a concept of how it should look. I just need to finish it, not really happy how it looks ATM.
![2016-03-23_11 22 05](https://cloud.githubusercontent.com/assets/16522707/14050945/ab07cab8-f27c-11e5-8efb-5f667eedd323.png)

**Comment by MrCompost** [comment]
Ok, so we need to get this polished up so we can compile the mod and release the new version. 
Here's what we need - 

Defo - 
Custom music (we have 3 tracks)
Config option for the menu/a button to switch back to the vanilla menu

Possibly - 
Custom button textures
Replace the dirt background in the other menus with something more fitting e.g temple brick
Any other small bits that people think of

Plus I'll tweak the textures here and there.

**Comment by TheCyberBrick** [comment]
Is this done?

**Comment by MrCompost** [comment]
There are a bunch of other things I wanted, but lets just leave this.

**Comment by TheCyberBrick** [comment]
And what are those other things?

**Comment by MrCompost** [comment]
Thinking about, the custom music ought to be done really since the tracks have been done already. I also read replies, and noticed myself, that the banner appears reeeaaaally small on bigger screens so it probably needs scaling up depending on that. 

Apart from that, I was thinking of replacing the textures for the buttons as well as the dirt background in the sub menus but we needn't do that really. Oh, and there was the custom loading screen thing but that's another thing really.

**Comment by TheCyberBrick** [comment]
So, are there any button textures?
