### ISSUE TITLE
Marsh Biome decoration needs a little fixy

### ISSUE THREAD

**Issue by vadis365** [Angry-Pixel/The-Betweenlands#259]
I'll take a look at the decoration and see what is causing the lack of plant life.

**Comment by WightofShadows** [comment]
This also affects the Sludge Plains biome from what I've noticed.

**Comment by MrCompost** [comment]
I've noticed it in swamplands though its nowhere near as bad.

**Comment by TheCyberBrick** [comment]
It's happening where big structures are generating aka almost everywhere in the BL. Let me explain again: it's caused by a safety feature that I implemented that stops the game from crashing or getting stuck for a long time when generating terrain with big structures. That was mostly the case in the swamplands biome because there's a ton of trees. The whole biome would often generate all at once and interrupt the server until it was done generating, or in many cases also crash. This *might* be fixable by setting isTerrainPopulated (or whatever its called) in the border chunks to false. If that doesn't work then I don't see a simple way to fix it efficiently without going through the whole terrain decoration and tediously fix any offset or other things that cause adjacent chunks to load. Or maybe I just think it's tedious. Either way, I personally don't think it's worth doing if it's complicated, because we'll most likely rewrite it for the 1.9 update anyways

**Comment by vadis365** [comment]
Changes a few thing's offsets to honour chunk boundaries and it seems to have improved things.
Yes it was tedious.
