### ISSUE TITLE
Vanilla potions ought to be made useless

### ISSUE THREAD

**Issue by MrCompost** [Angry-Pixel/The-Betweenlands#276]
I was thinking maybe when you go through the portal, all potions get turned into "Tainted Potions", much like how the Rotten Food works. Thoughts?

**Comment by jredfox** [comment]
I think this is a terrible idea.  Potions and witches are associated with the swamp area and to make them all tainted would be going against the swamp.

**Comment by TheCyberBrick** [comment]
Shrek wouldn't be happy either

**Comment by MrCompost** [comment]
Except we developed our own whole potion system to replace it.

**Comment by jredfox** [comment]
well if you physically made a better brewing system / magic witchery stations then, I wouldn't care. otherwise don't do it.  What type of potions are you making from thebetweenlands, are they just the same default vanilla ones just replaces, or are they all new potions with all new abilities?  I think if it an't broke don't fix it.  I think you could still have a separate system for brewing your modded potions and even disable potian recipes if you are in that dimension and in the config file, have an option to use your system entirely.  if it an't better then vanilla then, don't  touch vanilla's code.

**Comment by TheCyberBrick** [comment]
Have you even tried it out yet?

**Comment by MrCompost** [comment]
Look, you clearly haven't even looked at our potion system, so any criticisms are pretty much void. Also why would we need to touch vanilla code?

**Comment by jredfox** [comment]
you were trying to touch vanilla code by making the potians tainted

**Comment by TheCyberBrick** [comment]
No, and the potions aren't affected if you aren't in the dimension anyways.
